CREATE TABLE rooms(id SERIAL PRIMARY KEY, name VARCHAR(100), description VARCHAR(250));


ALTER TABLE rooms
ALTER COLUMN name SET DATA TYPE VARCHAR(50),
ALTER COLUMN description SET DATA TYPE VARCHAR(500);